stocks/urls.py
from django.urls import path, register_converter
from . import converters, views

# Opstilling af nye url af typen float
register_converter(converters.FloatUrlParameterConverter, 'float')

# Dette angiver navnet på denne Django-applikation.
app_name = 'stocks'


# Denne liste mapper url endpoints til view funktioner (url configuration)
# Django kalder automatisk funktionerne når siden loades
urlpatterns = [
    path('', views.index, name='index'),
    path('sort-<str:sort>/', views.index, name='index'),
    path('search-<str:search>/', views.index, name='index'),
    path('<str:stock_ticker>/', views.detail, name='detail'),
    path('<str:stock_ticker>/buy', views.handle_transaction,
         name='handle_transaction'),
    path('<str:stock_ticker>/<int:quantity>/<float:price>/process',
         views.process, name='process'),
]

stocks/models.py
from datetime import datetime
from django.db import models


class Stock(models.Model):
    # Dette er en model til at repræsentere aktier.
    transactionDate = models.DateTimeField(default=datetime.now())
    ticker = models.CharField(max_length=255, default='')
    price = models.FloatField(max_length=255, default=0.0)

    def save(self, *args, **kwargs):
        # Transaktions datoen opdateres
        self.transactionDate = datetime.now().replace(second=0, microsecond=0)
        # Her kaldes den oprindelige .save funktion for at opdatere databasen.
        super(Stock, self).save(*args, **kwargs)

    class Meta:
        unique_together = ('ticker', 'price', 'transactionDate')
        # Definerer et unikt sammenhængende sæt af felter bestående af ticker, pris og transaktionsdato.

    def __str__(self):
        return self.ticker
        # Returnerer ticker-symbolet som strengrepræsentation af Stock-objektet.

stocks/views.py
from django.shortcuts import render
from datetime import datetime

# Importering af hjælpefunktioner og modeller
from StockWebsite.utils import API_call, quicksort, linear_search, create_graph, get_name_and_ticker, get_price
from portfolio.models import Order
from .models import Stock
from django.contrib.auth.decorators import login_required

# Opret dine views her.


def index(request, sort="", search=""):
    # Funktion for hovedsiden der kaldes når siden indlæses
    # API-kald for at hente data
    results = API_call(
        "https://api.polygon.io/v2/aggs/grouped/locale/us/market/stocks/2024-03-06?adjusted=true&apiKey=")

    # Sorter listen baseret på handelsvolumen ('v')
    sorted_results = quicksort(
        results, 0, len(results)-1, 'v', descending=True)

    # Vælg de 100 mest handlede aktier
    top_100_companies = sorted_results[:100]

    if sort == 'ticker':
        stocks = quicksort(top_100_companies, 0,
                           len(top_100_companies)-1, 'T')
    elif sort == 'price':
        stocks = quicksort(top_100_companies, 0,
                           len(top_100_companies)-1, 'c', descending=True)
    elif search:
        search_result = linear_search(top_100_companies, search.upper())
        if search_result != -1:
            stocks = [search_result]
        else:
            stocks = []
    else:
        stocks = top_100_companies

    # Retunerer skabelonen index.html
    return render(request, "stocks/index.html", {"stocks": stocks})


def detail(request, stock_ticker):
    # Detaljefunktion

    # API-anmodning for at hente data om aktien
    ticker_results = API_call(
        "https://api.polygon.io/v3/reference/tickers/", stock_ticker, "?apiKey=")

    # API-anmodning for at hente grafdata
    graph_data = API_call("https://api.polygon.io/v2/aggs/ticker/", stock_ticker,
                          "/range/1/day/2024-01-01/2024-04-01?adjusted=true&sort=asc&limit=120&apiKey=")

    # Opret graf og hent pris
    graph, price = create_graph(graph_data)

    # API-anmodning for at hente nyheder om aktien
    news = API_call(
        "https://api.polygon.io/v2/reference/news?ticker=", stock_ticker, "&limit=3&apiKey=")

    return render(request, 'stocks/detail.html', {'stock': ticker_results, 'graph': graph, 'price': price, 'news': news})


@login_required
def process(request, stock_ticker, quantity, price):
    # Funktion til at behandle en handel

    # Beregn prisen
    cost = quantity * price

    # Opret eller hent aktieobjekt fra databasen
    stock_obj, created = Stock.objects.get_or_create(
        price=price,
        ticker=stock_ticker,
        transactionDate=datetime.now().replace(second=0, microsecond=0)
    )

    # Opret en handelsordre
    order_obj = Order(quantity=quantity, user=request.user, stock=stock_obj)

    # Opdater brugerens saldo
    currentUser = request.user
    currentUser.balance = currentUser.balance-cost

    # Gem ændringerne i databasen
    order_obj.save()
    currentUser.save()

    return render(request, 'stocks/process_trade.html', {'stockTicker': stock_ticker, 'quantity': quantity, 'price': price})


@login_required
def handle_transaction(request, stock_ticker):
    # Funktion til at håndtere en transaktion

    # API-anmodning for at hente prisdata
    price_results = API_call("https://api.polygon.io/v2/aggs/ticker/", stock_ticker,
                             "/range/1/day/2024-01-01/2024-03-01?adjusted=true&sort=asc&limit=120&apiKey=")

    # API-anmodning for at hente data om aktien
    ticker_results = API_call(
        "https://api.polygon.io/v3/reference/tickers/", stock_ticker, "?apiKey=")

    # Hent pris og navn på aktien
    price = get_price(price_results)
    name, ticker = get_name_and_ticker(ticker_results)

    # Hent brugerens saldo
    balance = round(request.user.balance, 2)

    return render(request, 'stocks/handle_transaction.html', {'price': price, 'name': name, 'ticker': ticker, 'bal': balance})

stocks/templates/stocks/buy.html
{% extends "base.html" %} {% block content %}
<h1>{{name}} ({{ticker}})</h1>
<h2>Current price: {{price}}$</h2>

  
  <form 
  class="mb-3" 
  method="post" 

  id="buyForm" >
  {% csrf_token %}
    <label class="form-label">Quantity</label>
    
    <input
      type="number"
      class="form-control"
      value="{{quantity}}"
      name="quantity"
      id="quantity-input"
      oninput="calculateTotal()"
    />
  
  <h2>Total Price: <span id="total-price"></span></h2>
  <button type="submit" class="btn btn-success">Buy</button>
</form>

<script>
  var totalPrice=0
  var price=0
  var quantity=0
  function calculateTotal() {
      price = {{ price }};
      quantity = document.getElementById('quantity-input').value;
      totalPrice = price * quantity;
      document.getElementById('total-price').innerText = totalPrice.toFixed(2)+"$";
  }
 
  let buyForm = document.getElementById("buyForm");

//ALIS KODESTYKKE PIL IKKE

  buyForm.addEventListener("submit", (e) => {
    e.preventDefault();
    const user_balance={{user.balance}};

    if (totalPrice==0){
      alert("Please enter a valid amount!");
    }else if (totalPrice>user_balance){
      alert("Insufficient funds");
    }else{
      console.log("run")
      window.location.assign(`./${quantity}/buy/${price}/process`);
    }
    

    
  });
  
</script>
{% endblock %}

stocks/templates/stocks/detail.html
{% extends "base.html" %} {% block content %}
<div class="on my-3 p-3">
  <h1>{{stock.name}} ({{stock.ticker}})</h1>
  <h2>Currently trading for {{price}}$</h2>
  <p>{{stock.description}}</p>
  <a href="buy" class="btn btn-primary btn-lg">Buy</a>
  <div>{{ graph|safe }}</div>
</div>
<h2>Related News</h2>
<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for article in news %}
  <div class="col">
    <a href="{{ article.article_url }}" target="_blank" class="card-link">
      <div class="card h-100">
        <img
          src="{{ article.image_url }}"
          height="250px"
          class="card-img-top"
          alt="{{ article.title }}"
        />
        <div class="card-body">
          <p class="card-text" style="font-size: smaller">
            {{ article.publisher.name }}
          </p>
          <h5 class="card-title">{{ article.title }}</h5>
          <p class="card-text">{{ article.description |truncatechars:300 }}</p>
        </div>
        <div class="card-footer">
          <small class="text-body-secondary"
            >Published: {{ article.published_utc }}</small
          >
        </div>
      </div>
    </a>
  </div>
  {% endfor %}
</div>
<style>
  .card-link {
    text-decoration: none;
  }
</style>
{% endblock %}

stocks/templates/stocks/handle_transaction.html
{% extends "base.html" %} {% block content %}
<h1>{{name}} ({{ticker}})</h1>
<br />
<h2>Price: {{price}}$</h2>
<br />
<h2>Your current balance: {{bal}}$</h2>

<form class="mb-3" method="post" id="buyForm">
  {% csrf_token %}
  <label class="form-label mt-5">
    <h2>Quantity</h2>
  </label>

  <input
    type="number"
    class="form-control mb-5"
    value="{{quantity}}"
    name="quantity"
    id="quantity-input"
    oninput="calculateTotal()"
  />

  <h2>Total Price: <span id="total-price"></span></h2>
  <button type="submit" class="btn btn-primary btn-lg">Buy</button>
</form>

<script>
    var totalPrice=0
    var price=0
    var quantity=0
    function calculateTotal() {
        price = {{ price }};
        quantity = document.getElementById('quantity-input').value;
        totalPrice = price * quantity;
        if (quantity<0){
          document.getElementById('total-price').innerText="Please enter a valid amount"
        }else{
        document.getElementById('total-price').innerText = totalPrice.toFixed(2)+"$";
        }
    }

    let buyForm = document.getElementById("buyForm");
  //ALIS KODESTYKKE PIL IKKE

    buyForm.addEventListener("submit", (e) => {
      e.preventDefault();
      const user_balance={{user.balance}};
      if (quantity<=0){
        alert("Please enter a valid amount!");
      }else if (totalPrice>user_balance){
        alert("Insufficient funds");
      }else{
        window.location.assign(`./${quantity}/${price}/process`);
      }
    });
</script>
{% endblock %}

stocks/templates/stocks/index.html
{% extends "base.html" %} {% block content %} {% if stocks%}

<div class="d-flex align-items-center">
  <div class="dropdown">
    <a
      class="btn btn-secondary dropdown-toggle"
      href="#"
      role="button"
      data-bs-toggle="dropdown"
      aria-expanded="false"
    >
      Sort by
    </a>

    <ul class="dropdown-menu">
      <li>
        <a class="dropdown-item" href="/stocks/sort-ticker">Ticker symbol</a>
      </li>
      <li><a class="dropdown-item" href="/stocks/sort-price">Price</a></li>
    </ul>
  </div>

  <form class="d-flex ms-2" role="search" id="searchForm">
    <input
      class="form-control me-2"
      type="search"
      placeholder="Search ticker symbol"
      aria-label="Search"
      id="searchInput"
    />
    <button class="btn btn-outline-success" type="submit">Search</button>
  </form>
</div>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    {% for stock in stocks %}
    <tr>
      <td>
        <a href="{% url 'stocks:detail' stock.T %}">{{stock.T}}</a>
      </td>
      <td>{{stock.c}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<script>
  document
    .getElementById("searchForm")
    .addEventListener("submit", function (event) {
      event.preventDefault(); // Prevent default form submission
      var searchInput = document.getElementById("searchInput").value.trim(); // Get the trimmed value of the input field

      // Check if the search input is not empty
      if (searchInput !== "") {
        // Construct the URL and redirect
        window.location.href = "/stocks/search-" + searchInput.toUpperCase();
      } else {
        // Display an alert or perform other actions to handle empty search input
        alert("Please enter a ticker symbol to search.");
      }
    });
</script>

{% else %}
<p>
  We could not find the ticker symbol you are looking for. Press
  <a href="/stocks">here</a> to browse all stocks.
</p>
{% endif %} {% endblock %}

stocks/templates/stocks/process_trade.html
{% extends "base.html" %} {% block title %}Processing trade{% endblock title %}
{% block content %}
<div class="on my-3 p-3">
  <h1>
    Processing the purchase of {{quantity}} volume for the stock {{stockTicker}}
    at {{price}}$.
    <div class="spinner-border spinner-border-xl" role="status">
      <span class="sr-only"></span>
    </div>
    Please wait...
  </h1>

  {{index}}
</div>
<script>
  function delay(time) {
    return new Promise((resolve) => setTimeout(resolve, time));
  }
  delay(3000).then(() => window.location.assign("../../../../../portfolio"));
</script>

{% endblock content %}