stocks/urls.py
from django.urls import path, register_converter
from . import converters, views

# Opstilling af nye url af typen float
register_converter(converters.FloatUrlParameterConverter, 'float')

# Dette angiver navnet på denne Django-applikation.
app_name = 'stocks'


# Denne liste mapper url endpoints til view funktioner (url configuration)
# Django kalder automatisk funktionerne når siden loades
urlpatterns = [
    path('', views.index, name='index'),
    path('sort-<str:sort>/', views.index, name='index'),
    path('search-<str:search>/', views.index, name='index'),
    path('<str:stock_ticker>/', views.detail, name='detail'),
    path('<str:stock_ticker>/buy', views.handle_transaction,
         name='handle_transaction'),
    path('<str:stock_ticker>/<int:quantity>/<float:price>/process',
         views.process, name='process'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Wallstreet Wannabees</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <style>
      .zoom {
        transition: transform 0.4s;
        margin: 0 auto;
      }

      .zoom:hover {
        transform: scale(1.1);
      }
      #footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        height: 2.5rem;
      }
      #page-container {
        position: relative;
        min-height: 90vh;
      }

      #content-wrap {
        padding-bottom: 2rem; /* Footer height */
      }
    </style>
  </head>
  <body>
    <div id="page-container">
      <div id="content-wrap">
        <nav class="navbar bg-body-white px-3 border-bottom border-dark">
          <div class="navbar">
            <a class="navbar-brand" href="/">
              <img
                class="img-fluid px-2"
                style="height: 50px"
                src="https://img.freepik.com/premium-vector/ww-logo-design_705304-609.jpg"
              />
              Wallstreet Wannabees
            </a>

            <a href="/" class="nav-link px-2 text-muted zoom">Home</a>

            <a href="/stocks" class="nav-link px-2 text-muted zoom">Stocks</a>

            <a href="/portfolio/" class="nav-link px-2 text-muted zoom"
              >Portfolio</a
            >

            <a
              href="/accounts/{{user.username|yesno:'profile,login'}}"
              class="zoom nav-link px-2 text-muted"
              >{{user.username|yesno:'Profile,Login'}}</a
            >
          </div>
        </nav>

        <main class="container py-4 mains">
          {% block content %} {% endblock %}
        </main>

        <footer id="footer" class="py-3 my-4">
          <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item">
              <a href="/" class="nav-link px-2 text-muted zoom">Home</a>
            </li>
            <li class="nav-item">
              <a href="/stocks" class="nav-link px-2 text-muted zoom">Stocks</a>
            </li>
            <li class="nav-item">
              <a href="/portfolio/" class="nav-link px-2 text-muted zoom"
                >Portfolio</a
              >
            </li>

            <li class="nav-item">
              <a
                href="/accounts/{{user.username|yesno:'profile,login'}}"
                class="nav-link px-2 text-muted zoom"
                >{{user.username|yesno:'Profile,Login'}}</a
              >
            </li>
          </ul>
          <p class="text-center text-muted">
            &copy; 2024 Ali Asadi, Kasper Bankler & Victor Nordbjerg
          </p>
        </footer>
      </div>
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends "base.html" %} {% block content %}

<h1 class="display-1" align="center">Welcome to Wallstreet Wannabees!</h1>

<div class="centered">
  <p align="center">
    Click <a href="{% url 'stocks:index' %}">here</a> to browse our stocks
  </p>
</div>

<div>{{ graph|safe }}</div>

<figure align="center">
  <blockquote class="blockquote">
    <p>
      "The best time to start investing was yesterday, the second-best time is
      today."
    </p>
  </blockquote>
  <figcaption class="blockquote-footer">Warren Buffet</figcaption>
</figure>

<h2>News</h2>
<div class="row row-cols-1 row-cols-md-3 g-4">
  {% for article in news %}
  <div class="col">
    <a href="{{ article.article_url }}" target="_blank" class="card-link">
      <div class="card h-100">
        <img
          src="{{ article.image_url }}"
          height="250px"
          class="card-img-top"
          alt="{{ article.title }}"
        />
        <div class="card-body">
          <p class="card-text" style="font-size: smaller">
            {{ article.publisher.name }}
          </p>
          <h5 class="card-title">{{ article.title }}</h5>
          <p class="card-text">{{ article.description |truncatechars:300 }}</p>
        </div>
        <div class="card-footer">
          <small class="text-body-secondary"
            >Published: {{ article.published_utc }}</small
          >
        </div>
      </div>
    </a>
  </div>
  {% endfor %}
  <style>
    .card-link {
      text-decoration: none;
    }
    .centered {
      text-align: center;
      margin-top: 50px;
      margin-bottom: 50px;
    }
  </style>
  {% endblock %}
</div>